[package]
name = "tabletsupport"
version = "0.1.0"
authors = ["therealfarfetchd"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dbus = "0.6.4"
ksni = "0.0.0"
png = "0.15.0"